apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duolingo-clone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ASISHGOUDA/duolingo_clone.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: duolingo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
